#Here you can choose the name of the file. mp3 files supported only. Will get saved to the sounds folder
FileName: yooo.mp3

#Amount of time to get ready and move mouse. After this period, a confirmation sound plays once and a bounding box 20 pixels around dings
TimeToGetReady: 5

#The amount of seconds after your mouse leaves the invisible bounding box till the mp3 plays
AmountAfterLeave: 5

#Will the noise loop or only play once? ONCE or LOOP.
PlayParameters: ONCE