#Here you can choose the name of the file. mp3 files supported only. Will get saved to the sounds folder
FileName: scream.mp3

#Amount of time to get ready and move mouse. After this period, a confirmation sound plays once and if mouse moves, noise loops.
TimeToGetReady: 20

#TODO
#The amount of seconds after your mouse leaves till the mp3 plays (Not Implemented)
AmountAfterLeave: 5

#TODO
#Will the noise loop or only play once? ONCE or LOOP. (Not Implemented)
PlayParameters: ONCE